
name: CI/CD Integration - WebdriverIO
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Run
          uses: ianwalter/puppeteer-container@v4.0.0
          run: |
            cd ./solutions/02_Setup/webdriverio
            npm install
            npm run test
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: ./solutions/02_Setup/webdriverio/logs