
name: CI/CD Integration - WebdriverIO
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install
          uses: ianwalter/puppeteer-container@v4.0.0
          with:
            args: "cd ./solutions/02_Setup/webdriverio && npm install"
        - name: Test
          uses: ianwalter/puppeteer-container@v4.0.0
          with:
            args: "cd ./solutions/02_Setup/webdriverio && npm run test"
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: ./solutions/02_Setup/webdriverio/logs