
name: 06 CI/CD Integration - Puppeteer, Playwright, Testcafe
on:
  pull_request:
  push:
    branches:
      - devx
jobs:
  puppeteer:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies and run
      run: |
        cd ./solutions/02_Setup/puppeteer
        npm i
        npx saucectl run
      env:
        BUILD_ID: ${{ github.run_id }}
        BUILD_ENV: GitHub Actions
  playwright:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies and run
      run: |
        cd ./solutions/02_Setup/playwright
        npm i
        npx saucectl run
      env:
        BUILD_ID: ${{ github.run_id }}
        BUILD_ENV: GitHub Actions
  testcafe:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies and run
      run: |
        cd ./solutions/02_Setup/testcafe
        npm i
        npx saucectl run
      env:
        BUILD_ID: ${{ github.run_id }}
        BUILD_ENV: GitHub Actions