
name: CICD For All Tools
# Triggers the workflow on push or pull request events
on: [push, pull_request]
# Sets environment variable values for the workflow
env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  SCREENER_API_KEY: ${{ secrets.SCREENER_API_KEY }}
jobs:
  webdriverio:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run WebdriverIO Tests
      run: |
        cd ./solutions/07_Cloud_Integration/webdriverio
        npm install
        npm run test
  cypress:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 14.x
        - name: Install dependencies and run
          run: |
            cd ./solutions/02_Setup/cypress
            npm i
            npx saucectl run --test-env sauce
          env:
            BUILD_ID: ${{ github.run_id }}
            BUILD_ENV: GitHub Actions
  screener:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run WebdriverIO Tests
      run: |
        cd ./solutions/08_Visual_E2E/webdriverio
        npm install
        npm run test
  #Similar set up for all the other frameworks
  # playwright:
  #       - name: Install dependencies and run
  #         run: |
  #           cd ./solutions/02_Setup/playwright
  #           npm i
  #           npx saucectl run --test-env sauce